site_name: Pegase
site_description: An inline, fast, powerful and lightweight PEG parser generator for JavaScript and TypeScript, with semantic actions, parametrized rules, support for native regexps, error recovery, warnings, integrated AST generation and visitors, cut operator, back references, grammar merging, and a lot more.
repo_url: https://github.com/strblr/pegase
repo_name: pegase
edit_uri: ""
site_url: https://strblr.github.io/pegase/
copyright: © strblr
nav:
  - Home: index.md
  - Basic concepts:
      - basic-concepts/Building-parsers.md
      - basic-concepts/Semantic-action-and-dataflow.md
      - basic-concepts/Handling-whitespaces.md
      - basic-concepts/Tokens.md
      - basic-concepts/Directives.md
      - basic-concepts/Failures-and-warnings.md
  - Advanced concepts:
      - advanced-concepts/Parametrized-rules.md
      - advanced-concepts/AST-and-visitors.md
      - advanced-concepts/Working-with-RegExp.md
      - advanced-concepts/Cut-operator.md
      - advanced-concepts/Debugging-with-tracers.md
      - advanced-concepts/Using-TypeScript.md
      - advanced-concepts/Error-recovery.md
      - advanced-concepts/Grammar-fragments.md
      - advanced-concepts/Writing-a-plugin.md
      - advanced-concepts/Writing-a-Parser-subclass.md
      - advanced-concepts/L-attributed-grammars.md
  - API:
      - api/peg-createTag.md
      - api/Parser.md
      - api/defaultPlugin.md
      - api/Hooks.md
      - api/Utility-functions.md
      - api/Types.md
      - api/Metagrammar.md
  - More:
      - more/Ideas.md
      - more/Bug-report-and-discussion.md
theme:
  name: material
  logo: assets/images/logo.png
  custom_dir: overrides
  font:
    text: Inter
  palette:
    scheme: default
    primary: black
  features:
    - toc.integrate
    - navigation.top
  icon:
    repo: fontawesome/brands/github-square
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/strblr/pegase
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://unpkg.com/pegase@0.5.3/umd/index.js
  - javascript/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/nord.min.css
  - https://fonts.googleapis.com/css?family=Inter
  - css/style.css
