site_name: Pegase
site_description: An inline, powerful and lightweight PEG parser generator for JavaScript and TypeScript, with semantic actions, support for native regexps, error recovery, warnings, grammar fragments, AST generation, AST visitors, cut operator, and a lot more.
copyright: © ostrebler
nav:
  - Home: index.md
  - quick-start.md
  - Basic concepts:
      - basic-concepts/Building-parsers.md
      - basic-concepts/Semantic-action-and-dataflow.md
      - basic-concepts/Handling-whitespaces.md
      - basic-concepts/Tokens.md
      - basic-concepts/Directives.md
      - basic-concepts/Failures-and-warnings.md
  - Advanced concepts:
      - advanced-concepts/AST-and-visitors.md
      - advanced-concepts/Working-with-RegExp.md
      - advanced-concepts/Cut-operator.md
      - advanced-concepts/Debugging-with-tracers.md
      - advanced-concepts/Using-TypeScript.md
      - advanced-concepts/Grammar-fragments.md
      - advanced-concepts/Error-recovery.md
      - advanced-concepts/Writing-a-plugin.md
      - advanced-concepts/Writing-a-Parser-subclass.md
      - advanced-concepts/L-attributed-grammars.md
  - API:
      - api/peg-createTag.md
      - api/Parser.md
      - api/Logger.md
theme:
  name: material
  logo: assets/images/logo.png
  custom_dir: overrides
  palette:
    scheme: default
    primary: red
  features:
    - navigation.expand
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ostrebler/pegase
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascript/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/atom-one-dark.min.css
